# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
 - job: Windows_64_Bit
   pool:
     vmImage: 'windows-latest'
   steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Cache@2
      inputs:
        key: 'gradle | "$(Agent.OS)" | $(Build.SourcesDirectory)/build.gradle | $(Build.SourcesDirectory)/settings.gradle | $(Build.SourcesDirectory)/gradle/wrapper/gradle-wrapper.properties | $(Build.SourcesDirectory)/vendordeps'
        path: $(GRADLE_USER_HOME)
      displayName: 'Cache Gradle dependencies'
    - task: Gradle@3
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build --stacktrace --info'
      env:
        GRADLE_USER_HOME: $(GRADLE_USER_HOME)
    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
        reportDirectory: 'build/reports/jacoco/test/html'
    - task: MavenAuthenticate@0
      displayName: 'Maven Authenticate'
      inputs:
        artifactsFeeds: XBot
    - task: Gradle@2
      displayName: 'Publish to Maven'
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        tasks: 'publish --info'
      env:
        GRADLE_USER_HOME: $(GRADLE_USER_HOME)
    - task: Gradle@2
      displayName: Generate Javadoc
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        tasks: 'javadoc'
      env:
        GRADLE_USER_HOME: $(GRADLE_USER_HOME)
    - task: PublishPipelineArtifact@0
      displayName: 'Publish javadoc as an artifact'
      inputs:
        artifactName: 'javadoc'
        targetPath: 'build/docs/javadoc'
