# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
 - job: Windows_64_Bit
   pool:
     vmImage: 'windows-latest'
   steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build --stacktrace --info'
        # checkStyleRunAnalysis: true
        # pmdRunAnalysis: true
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
        reportDirectory: 'build/reports/jacoco/test/html'
    - task: MavenAuthenticate@0
      displayName: 'Maven Authenticate'
      inputs:
        artifactsFeeds: XBot
    - task: Gradle@2
      displayName: 'Publish to Maven'
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        tasks: 'publish --info'
    - task: Gradle@2
      displayName: Generate Javadoc
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        tasks: 'javadoc'
    - task: PublishPipelineArtifact@0
      displayName: 'Publish javadoc as an artifact'
      inputs:
        artifactName: 'javadoc'
        targetPath: 'build/docs/javadoc'
    - task: PublishHtmlReport@3
      displayName: 'Publish SpotBugs report'
      inputs:
        tabName: "SpotBugs"
        reportDir: 'build/reports/spotbugs/main.html'
